// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit.
// Maps image-slot ids to the file found in /public/images at build time.

export const RESOLVED: Record<string, string> = {};

export function resolveImage(id: string): string | null {
  return RESOLVED[id] ?? null;
}
