/**
 * Scans /public/images and records which declared image slots actually have a
 * file on disk.
 *
 * Runs before `dev` and `build`. It is what lets photography be dropped in
 * later with no code change: sections read the generated map and render either
 * the real <Image> or the labelled pending frame.
 *
 * Accepts .jpg / .jpeg / .webp / .avif / .png for a slot declared as .jpg, so
 * the brief's file names work whatever format the photographer delivers.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = path.join(root, "public", "images");
const manifestPath = path.join(root, "src", "content", "images.ts");
const outPath = path.join(root, "src", "content", "images.generated.ts");

const EXTENSIONS = [".jpg", ".jpeg", ".webp", ".avif", ".png"];

// Read the slot ids straight out of the manifest so the two cannot drift.
const manifest = fs.readFileSync(manifestPath, "utf8");
const ids = [...manifest.matchAll(/slot\("([a-z0-9-]+)"/gi)].map((m) => m[1]);

const present = fs.existsSync(imagesDir) ? fs.readdirSync(imagesDir) : [];

/** @type {Record<string, string>} slot id -> public path of the found file */
const found = {};
for (const id of ids) {
  const match = present.find((f) => {
    const ext = path.extname(f).toLowerCase();
    return path.basename(f, ext) === id && EXTENSIONS.includes(ext);
  });
  if (match) found[id] = `/images/${match}`;
}

const body = `// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit.
// Maps image-slot ids to the file found in /public/images at build time.

export const RESOLVED: Record<string, string> = ${JSON.stringify(found, null, 2)};

export function resolveImage(id: string): string | null {
  return RESOLVED[id] ?? null;
}
`;

const previous = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
if (previous !== body) fs.writeFileSync(outPath, body);

const total = ids.length;
const have = Object.keys(found).length;
console.log(
  `[assets] ${have}/${total} image slots resolved` +
    (have < total
      ? ` — missing: ${ids.filter((id) => !found[id]).join(", ")}`
      : ""),
);
